const { colors } = require('tailwindcss/defaultTheme');
module.exports = {
  purge: ['src/**/*.js', 'src/**/*.jsx', 'src/**/*.ts', 'src/**/*.tsx'],
  theme: {
    container: {
      center: true,
    },
    extend: {
      spacing: {
        30: '7.5rem',
        72: '18rem',
        80: '20rem',
        88: '22rem', // 88/4
        '1/4': '25%',
        '1/3': '33.333333%',
        '1/2': '50%',
        '2/3': '66.666667%',
        '3/4': '75%',
        '5/6': '83%',
        '11/12': '91%',
        '4xs': '8rem',
        '3xs': '12rem',
        '2xs': '16rem',
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
      },
      maxWidth: {
        '1/8': '12.5',
        '1/6': '16.666666%',
        '1/5': '20%',
        '1/4': '25%',
        '1/3': '33.333333%',
        '1/2': '50%',
        '2/3': '66.666667%',
        '3/4': '75%',
        '5/6': '83%',
        '11/12': '91%',
      },
      maxHeight: (theme, { breakpoints }) => ({
        none: 'none',
        '4xs': '8rem',
        '3xs': '12rem',
        '2xs': '16rem',
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        full: '100%',
        ...breakpoints(theme('screens')),
      }),
      colors: {
        blue: {
          '050': '#DCEEFB',
          100: '#B6E0FE',
          200: '#84C5F4',
          300: '#62B0E8',
          400: '#4098D7',
          500: '#2680C2',
          600: '#186FAF',
          700: '#0F609B',
          800: '#0A558C',
          900: '#003E6B',
        },
        primary: {
          '050': '#DCEEFB',
          100: '#B6E0FE',
          200: '#84C5F4',
          300: '#62B0E8',
          400: '#4098D7',
          500: '#2680C2',
          600: '#186FAF',
          700: '#0F609B',
          800: '#0A558C',
          900: '#003E6B',
        },
        'blue-grey': {
          '050': '#F0F4F8',
          100: '#D9E2EC',
          200: '#BCCCDC',
          300: '#9FB3C8',
          400: '#829AB1',
          500: '#627D98',
          600: '#486581',
          700: '#334E68',
          800: '#243B53',
          900: '#102A43',
        },
        secondary: {
          '050': '#F0F4F8',
          100: '#D9E2EC',
          200: '#BCCCDC',
          300: '#9FB3C8',
          400: '#829AB1',
          500: '#627D98',
          600: '#486581',
          700: '#334E68',
          800: '#243B53',
          900: '#102A43',
        },
        'teal-vivid': {
          '050': '#F0FCF9',
          100: '#C6F7E9',
          200: '#8EEDD1',
          300: '#5FE3C0',
          400: '#2DCCA7',
          500: '#17B897',
          600: '#079A82',
          700: '#048271',
          800: '#016457',
          900: '#004440',
        },
        tertiary: colors.indigo,
        red: {
          '050': '#FFEEEE',
          100: '#FACDCD',
          200: '#F29B9B',
          300: '#E66A6A',
          400: '#D64545',
          500: '#BA2525',
          600: '#A61B1B',
          700: '#911111',
          800: '#780A0A',
          900: '#610404',
        },
        yellow: {
          '050': '#FFFAEB',
          100: '#FCEFC7',
          200: '#F8E3A3',
          300: '#F9DA8B',
          400: '#F7D070',
          500: '#E9B949',
          600: '#C99A2E',
          700: '#A27C1A',
          800: '#7C5E10',
          900: '#513C06',
        },
      },
    },
    customForms: (theme) => ({
      dark: {
        'input, textarea, multiselect, checkbox, radio': {
          backgroundColor: theme('colors.gray.900'),
          color: '#fff',
        },
        select: {
          backgroundColor: theme('colors.gray.600'),
        },
      },
      sm: {
        'input, textarea, multiselect, select': {
          fontSize: theme('fontSize.sm'),
          padding: `${theme('spacing.1')} ${theme('spacing.2')}`,
        },
        select: {
          paddingRight: `${theme('spacing.4')}`,
        },
        'checkbox, radio': {
          width: theme('spacing.3'),
          height: theme('spacing.3'),
        },
      },
    }),
    spinner: (theme) => ({
      primary: {
        color: theme('colors.primary.600', 'primary'),
        size: '2rem',
        border: '3px',
        speed: '400ms',
      },
      secondary: {
        color: theme('colors.secondary.400', 'secondary'),
        size: '2rem',
        border: '3px',
        speed: '400ms',
      },
      white: {
        color: '#fff',
        size: '2rem',
        border: '3px',
        speed: '400ms',
      },
    }),
  },

  plugins: [
    require('@tailwindcss/custom-forms'),
    require('tailwindcss-spinner')(),
    require('@tailwindcss/typography'),
    function ({ addVariant }) {
      addVariant('important', ({ container }) => {
        container.walkRules((rule) => {
          rule.selector = `.\\i-${rule.selector.slice(1)}`;
          rule.walkDecls((decl) => {
            decl.important = true;
          });
        });
      });
    },
    function ({ addUtilities }) {
      const newUtils = {
        '.grow-2xs': {
          transform: 'scale(1.025)',
          transition: 'transform 0.3s ease-in-out',
        },
        '.grow-xs': {
          transform: 'scale(1.05)',
          transition: 'transform 0.3s ease-in-out',
        },
        '.grow-sm': {
          transform: 'scale(1.15)',
          transition: 'transform 0.3s ease-in-out',
        },
        '.rounded-xl': {
          borderRadius: '0.75rem',
        },
      };

      addUtilities(newUtils, {
        variants: ['responsive', 'hover', 'important'],
      });
    },
    function ({ addUtilities }) {
      const newUtils = {
        '.screen-center': {
          position: 'fixed',
          left: '50%',
          top: '50%',
          transform: 'translate(-50%, -50%)',
        },
        '.screen-top-third': {
          position: 'fixed',
          left: '50%',
          top: '33%',
          transform: 'translate(-50%, -30%)',
        },
        '.screen-top-quarter': {
          position: 'fixed',
          left: '50%',
          top: '25%',
          transform: 'translate(-50%, -50%)',
        },
        '.screen-top-tenth': {
          position: 'fixed',
          left: '50%',
          top: '10%',
          transform: 'translate(-50%, -50%)',
        },
        '.top-50-p': {
          top: '50%',
        },
        '.left-50-p': {
          left: '50%',
        },
        '.right-50-p': {
          right: '50%',
        },
        '.bottom-50-p': {
          bottom: '50%',
        },
      };

      addUtilities(newUtils, {
        variants: ['responsive', 'hover', 'important'],
      });
    },
  ],
  variants: {
    alignContent: ['responsive', 'important'],
    alignItems: ['responsive', 'important'],
    alignSelf: ['responsive', 'important'],
    appearance: ['responsive', 'important'],
    backgroundAttachment: ['responsive', 'important'],
    backgroundColor: ['responsive', 'important', 'hover', 'focus'],
    backgroundPosition: ['responsive', 'important'],
    backgroundRepeat: ['responsive', 'important'],
    backgroundSize: ['responsive', 'important'],
    borderCollapse: ['responsive', 'important', 'hover'],
    borderColor: ['responsive', 'important', 'hover', 'focus'],
    borderRadius: ['responsive', 'important', 'hover'],
    borderStyle: ['responsive', 'important', 'hover'],
    borderWidth: ['responsive', 'important', 'hover'],
    boxShadow: ['responsive', 'important', 'hover', 'focus'],
    cursor: ['responsive', 'important'],
    display: ['responsive', 'important'],
    fill: ['responsive', 'important'],
    flex: ['responsive', 'important'],
    flexDirection: ['responsive', 'important'],
    flexGrow: ['responsive', 'important'],
    flexShrink: ['responsive', 'important'],
    flexWrap: ['responsive', 'important'],
    float: ['responsive', 'important'],
    fontFamily: ['responsive', 'important'],
    fontSize: ['responsive', 'important'],
    fontSmoothing: ['responsive', 'important'],
    fontStyle: ['responsive', 'important'],
    fontWeight: ['responsive', 'important', 'hover', 'focus'],
    height: ['responsive', 'important'],
    inset: ['responsive', 'important'],
    justifyContent: ['responsive', 'important'],
    letterSpacing: ['responsive', 'important'],
    lineHeight: ['responsive', 'important'],
    listStylePosition: ['responsive', 'important'],
    listStyleType: ['responsive', 'important'],
    margin: ['responsive', 'important'],
    maxHeight: ['responsive', 'important'],
    maxWidth: ['responsive', 'important'],
    minHeight: ['responsive', 'important'],
    minWidth: ['responsive', 'important'],
    objectFit: ['responsive', 'important'],
    objectPosition: ['responsive', 'important'],
    opacity: ['responsive', 'important', 'hover', 'focus'],
    order: ['responsive', 'important'],
    outline: ['responsive', 'important', 'focus'],
    overflow: ['responsive', 'important'],
    padding: ['responsive', 'important'],
    placeholderColor: ['responsive', 'important', 'focus', 'hover', 'active'],
    pointerEvents: ['responsive', 'important'],
    position: ['responsive', 'important'],
    resize: ['responsive', 'important'],
    spinner: ['responsive', 'important'],
    stroke: ['responsive', 'important'],
    tableLayout: ['responsive', 'important'],
    textAlign: ['responsive', 'important'],
    textColor: ['responsive', 'important', 'hover', 'focus'],
    textDecoration: ['responsive', 'important', 'hover', 'focus'],
    textTransform: ['responsive', 'important'],
    userSelect: ['responsive', 'important'],
    verticalAlign: ['responsive', 'important'],
    visibility: ['responsive', 'important'],
    whitespace: ['responsive', 'important'],
    width: ['responsive', 'important'],
    wordBreak: ['responsive', 'important'],
    zIndex: ['responsive', 'important'],
  },
};
